### PR TITLE
Add continuous integration & delivery (CI+CD)

### PR DESCRIPTION
**Pull request by justinmayer**
Enables automatic test+linting checks on new commits and pull requests, as well as release publication to PyPI upon pull requests merge when an appropriate RELEASE.md file is present. Powered by GitHub Actions and [AutoPub](http://github.com/autopub/autopub).

### CODE REVIEW

**Comment by oulenz** [comment]
Thank you for setting this up!

I didn't have time before to check out your autopub project, but I did now, and I like it very much! I've struggled before with the inelegance of having to synchronise updating the version number and doing the actual release, and this is a very convenient solution.

**Comment by justinmayer** [comment]
My pleasure! Glad to hear it. This configuration has been a joy to use — add a `RELEASE.md` file to any commit, and when it lands in master the release is handled automatically without any intervention. Feels like magic and makes me smile every time. 😀

**Comment by oulenz** [comment]
One thing I'm still wondering: how exactly is publishing to pipy configured?

- Is the name specified somewhere, or automatically composed (pelican-more-categories)?
- I feel as though there isn't enough information in the config for poetry/autopub to know where to publish to.
- On that topic, I notice that the above config is using poetry to build and publish, not autopub. Why is that / what is the division of labour between the two?
- I'd like to manually publish version 0.0.0 to pipy, is that possible?

**Comment by justinmayer** [comment]
> Is the name specified somewhere, or automatically composed (pelican-more-categories)?

In keeping with convention, it is indeed `pelican-more-categories`, specified in `pyproject.toml`: https://github.com/pelican-plugins/more-categories/blob/master/pyproject.toml#L2

> I feel as though there isn't enough information in the config for poetry/autopub to know where to publish to.

I'm not sure what you mean by "where" here. If you mean to which repository URL, it would be the production PyPI instance. Other repository end-points can be specified via the `poetry publish --repository […]` option: https://python-poetry.org/docs/cli/#publish But in general, all the needed configuration is present in the `pyproject` file (aside from PyPI authentication credentials, which are in GitHub repo > Settings > Secrets > `PYPI_PASSWORD` env var).

> On that topic, I notice that the above config is using poetry to build and publish, not autopub. Why is that / what is the division of labour between the two?

Poetry does a good job at incrementing versions, building, and publishing, so there really wasn't any reason to replicate that functionality in AutoPub. Instead, I focused AutoPub on the other parts that Poetry (quite justifiably) does not attempt to handle: looking for release files and extracting needed information from them, updating duplicate version strings not handled by Poetry (for legacy projects that can't solely consolidate that number in `pyproject.toml`), writing the release description as a new entry in the change-log, committing and tagging those changes, and creating the GitHub release entry.

> I'd like to manually publish version 0.0.0 to pipy, is that possible?

It is possible. Normally, I use AutoPub to handle that because it also automates the creation of the initial `CHANGELOG.md` file, using the formatting that AutoPub expects. (See other plugins' change-logs under this org to see what they look like.) Doing it that way also ensures that subsequent publication happens seamlessly, as the authentication token used to register the package for the first time will automatically be accepted for subsequent releases. That said, if you still wish to publish version 0.0.0 manually, I'd be happy to provide that token to you so you can pass it via: `poetry publish -u __token__ -p <the-actual-token>`

Does that help? What further insight can I provide?

**Comment by oulenz** [comment]
Thanks, that makes sense!

> Poetry does a good job at incrementing versions, building, and publishing, so there really wasn't any reason to replicate that functionality in AutoPub. Instead, I focused AutoPub on the other parts that Poetry (quite justifiably) does not attempt to handle: looking for release files and extracting needed information from them, updating duplicate version strings not handled by Poetry (for legacy projects that can't solely consolidate that number in `pyproject.toml`), writing the release description as a new entry in the change-log, committing and tagging those changes, and creating the GitHub release entry.

But autopub has build and publish commands?

> It is possible. Normally, I use AutoPub to handle that because it also automates the creation of the initial `CHANGELOG.md` file, using the formatting that AutoPub expects. (See other plugins' change-logs under this org to see what they look like.) Doing it that way also ensures that subsequent publication happens seamlessly, as the authentication token used to register the package for the first time will automatically be accepted for subsequent releases. That said, if you still wish to publish version 0.0.0 manually, I'd be happy to provide that token to you so you can pass it via: `poetry publish -u __token__ -p <the-actual-token>`

Yes please!

**Comment by justinmayer** [comment]
AutoPub abstracts the build process because some projects still use Setuptools: https://github.com/autopub/autopub/blob/master/autopub/build_release.py#L8-L11

Same with the publish process: https://github.com/autopub/autopub/blob/master/autopub/publish_release.py#L15-L18

I'll send you the token now...

**Pull request merged**
